name: Docker

on:
  workflow_dispatch:
    inputs:
      context:
        description: Context
        required: true
        type: choice
        options:
          - hasura-cli
          - hasura-cli/distroless
          - hasura-wait4x

      version:
        description: Version
        type: string

jobs:
  metadata:
    runs-on: ubuntu-latest
    outputs:
      image_name: ${{ steps.set-var.outputs.image_name }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - id: set-var
        run: ./${{ inputs.context }}/metadata.sh
        env:
          Image_Version: ${{ inputs.version }}

  docker:
    needs: metadata
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      image_name: ${{ needs.metadata.outputs.image_name }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push latest
        uses: docker/build-push-action@v3
        with:
          context: ${{ inputs.context }}
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            VERSION=${{ inputs.version }}
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.image_name }}
            ghcr.io/${{ github.repository_owner }}/${{ env.image_name }}
