name: Docker

on:
  schedule:
    - cron: "37 19 * * 0"
  workflow_dispatch:
    inputs:
      context:
        description: Context
        type: choice
        options:
          - hasura-cli
          - hasura-wait4x
          - kopia
          - watchtower
      versions:
        description: Versions (separator ";")
        type: string
      variants:
        description: Variants (separator ";")
        type: string

jobs:
  metadata:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Generate matrix
        id: set-matrix
        run: python strategy.py
        env:
          context: ${{ github.event.inputs.context }}
          versions: ${{ github.event.inputs.versions }}
          variants: ${{ github.event.inputs.variants }}

  docker:
    needs: metadata
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix: ${{ fromJSON(needs.metadata.outputs.matrix) }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push latest
        uses: docker/build-push-action@v3
        with:
          context: ${{ matrix.context }}
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: ${{ matrix.args }}
          target: ${{ matrix.target }}
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.image }}
            ghcr.io/${{ github.repository_owner }}/${{ matrix.image }}
